---
# vars file for deploy-vega-service
# For script
release_name: "{{ network_alias_vega_rasa_nlp_sandbox_service }}"
user_friendly_name: vega service
#template_compose_file_name: ui-spv-igot.j2
template_env_file_name: "../../shared_files/templates/ui-shared-env.j2"
compose_file_name: "{{ service_vega_rasa_nlp_sandbox_service }}.yml"
env_file_name: "{{ service_vega_rasa_nlp_sandbox_service }}.env"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_vega_rasa_nlp_sandbox_service }}.env"
#chart_path: "../kubernetes-deploy/vega-rasa-nlp-sandbox-service"

env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"

# For service
application_port: "{{ service_vega_rasa_nlp_sandbox_port }}"
image_name: "{{ image_vega_rasa_nlp_sandbox_service }}"
tag: "{{ tags_vega_rasa_nlp_sandbox_service }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_vega_rasa_nlp_sandbox_service }}"
reserved_memory: "{{ service_mem_reserved_vega_rasa_nlp_sandbox_service }}"
limited_memory: "{{ service_mem_limit_vega_rasa_nlp_sandbox_service }}"
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/healthcheck
network_alias_name: "{{ network_alias_vega_rasa_nlp_sandbox_service }}"
docker_service_stack_name: ui
docker_service_name: "{{ service_vega_rasa_nlp_sandbox_service }}"
force_reload: "{{ force_reload_vega_rasa_nlp_sandbox_service }}"

