---
# vars file for deploy-ui-static
# For script
release_name: "{{ network_alias_frac_collab_service }}"
user_friendly_name: UI Frac-collab service
template_compose_file_name: ui-frac-wev.j2
template_env_file_name: "../../shared_files/templates/ui-shared-env.j2"
compose_file_name: "{{ service_frac_collab_service }}.yml"
env_file_name: "{{ service_frac_collab_service }}.env"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_frac_collab_service }}.env"
#chart_path: "../kubernetes-deploy/frac-collab-service"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"

# For service
application_port: "{{ service_frac_collab_service_port }}"
image_name: "{{ image_frac_collab_service }}"
tag: "{{ tags_frac_collab_service }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_frac_collab_service }}"
reserved_memory: "{{ service_mem_reserved_frac_collab_service }}"
limited_memory: "{{ service_mem_limit_frac_collab_service }}"
#health_check_endpoint: http://127.0.0.1:{{ docker_port }}/healthcheck
network_alias_name: "{{ network_alias_frac_collab_service }}"
docker_service_stack_name: ui
docker_service_name: "{{ service_frac_collab_service }}"
force_reload: "{{ force_reload_frac_collab_service }}"
