---
# vars file for deploy-lex-core-service

# For script
release_name: "{{ network_alias_sb_hub_graph_service }}"
template_compose_file_name: sb-hub-graph-service.j2
template_env_file_name: sb-hub-graph-service-env.j2
compose_file_name: "{{ service_sb_hub_graph_service }}.yml"
env_file_name: "{{ service_sb_hub_graph_service }}.env"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_sb_hub_graph_service }}.env"
#chart_path: "../kubernetes-deploy/hub-graph-service"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
user_friendly_name: Sb Hub service

# For service
application_port: "{{ service_sb_hub_graph_port }}"
image_name: "{{ image_sb_hub_graph_service }}"
tag: "{{ tags_sb_hub_graph_service }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_sb_hub_graph_service }}"
reserved_memory: "{{ service_mem_reserved_sb_hub_graph_service }}"
limited_memory: "{{ service_mem_limit_sb_hub_graph_service }}"
#limited_memory: 2048M
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/actuator/health
network_alias_name: "{{ network_alias_sb_hub_graph_service }}"
docker_service_stack_name: lms
docker_service_name: "{{ service_sb_hub_graph_service }}"
force_reload: "{{ force_reload_sb_hub_graph_service }}"

# For application
server_connection_timeout: 5000
tomcat_max_threads: 400
tomcat_min_spare_threads: 20
servlet_multipart_max_file_size: 100Mb
servlet_multipart_max_request_size: 100Mb

neo4j_url: "bolt://{{ neo4j_host }}:{{ neo4j_port }}"
kafka_ip: "http://{{ kafka_servers_list }}"
