---
# vars file for deploy-static-domian
# For script
release_name: "{{ network_alias_static_domian_service }}"
user_friendly_name: Static Domain service
template_compose_file_name: static-domain.j2
template_env_file_name: "configurations.json.j2"
compose_file_name: "{{ service_static_domian_service }}.yml"
env_file_name: "{{ service_static_domian_service }}.env"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
helm_env_file_location: "../helm_charts/igot-deploy/templates"
helm_env_file_name: "{{ helm_env_file_location }}/configurations.json"
helm_env_file_name1: "{{ helm_env_file_location }}/content-list-data.json"
#chart_path: "../kubernetes-deploy/ui-static"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"

# For service
application_port: "{{ service_static_domian_port }}"
image_name: "{{ image_static_domian }}"
tag: "{{ tags_static_domian }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_static_domian_service }}"
reserved_memory: "{{ service_mem_reserved_static_domian_service }}"
limited_memory: "{{ service_mem_limit_static_domian_service }}"
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/healthcheck
network_alias_name: "{{ network_alias_static_domian_service }}"
docker_service_stack_name: ui
docker_service_name: "{{ service_static_domian_service }}"
force_reload: "{{ force_reload_static_domian_service }}"
