---
# defaults file for deploy-ui-static

# redis keys updated by LP script
redis_key_lp_update_time: "lp_update_time"
redis_key_lp_es_user_count: "lp_es_user_count"
redis_key_lp_es_org_count: "lp_es_org_count"
redis_key_lp_es_live_course_count: "lp_es_live_course_count"
redis_key_lp_es_agg_course_duration: "lp_es_agg_course_duration"
redis_key_lp_es_live_course_id_list: "lp_es_live_course_id_list"
redis_key_lp_es_live_course_publisher_count: "lp_es_live_course_publisher_count"

redis_key_lp_es_draft_course_count: "lp_es_draft_course_count"
redis_key_lp_es_review_course_count: "lp_es_review_course_count"
redis_key_lp_es_retired_course_count: "lp_es_retired_course_count"
redis_key_lp_es_pending_publish_course_count: "lp_es_pending_publish_course_count"

# redis keys not updated by LP script, here for reference
redis_key_dashboard_update_time: "dashboard_update_time"
redis_key_dashboard_courses_enrolled_in_at_least_once: "dashboard_courses_enrolled_in_at_least_once"
redis_key_dashboard_courses_completed_at_least_once: "dashboard_courses_completed_at_least_once"
redis_key_dashboard_courses_enrolled_in_at_least_once_id_list: "dashboard_courses_enrolled_in_at_least_once_id_list"
redis_key_dashboard_courses_completed_at_least_once_id_list: "dashboard_courses_completed_at_least_once_id_list"

redis_key_dashboard_enrolment_count: "dashboard_enrolment_count"
redis_key_dashboard_completed_count: "dashboard_completed_count"

redis_key_dashboard_unique_users_enrolled_count: "dashboard_unique_users_enrolled_count"
redis_key_dashboard_unique_users_completed_count: "dashboard_unique_users_completed_count"

redis_key_dashboard_new_users_registered_yesterday: "dashboard_new_users_registered_yesterday"

# redis hashmap keys not updated by LP script, here for reference
redis_key_dashboard_user_count_by_user_org: "dashboard_user_count_by_user_org"
redis_key_dashboard_live_course_count_by_course_org: "dashboard_live_course_count_by_course_org"

redis_key_dashboard_draft_course_count_by_course_org: "dashboard_draft_course_count_by_course_org"
redis_key_dashboard_review_course_count_by_course_org: "dashboard_review_course_count_by_course_org"
redis_key_dashboard_retired_course_count_by_course_org: "dashboard_retired_course_count_by_course_org"
redis_key_dashboard_pending_publish_course_count_by_course_org: "dashboard_pending_publish_course_count_by_course_org"

redis_key_dashboard_enrolment_count_by_user_org: "dashboard_enrolment_count_by_user_org"
redis_key_dashboard_completed_count_by_user_org: "dashboard_completed_count_by_user_org"

redis_key_dashboard_enrolment_count_by_course_org: "dashboard_enrolment_count_by_course_org"
redis_key_dashboard_completed_count_by_course_org: "dashboard_completed_count_by_course_org"

redis_key_lp_monthly_active_users: "lp_monthly_active_users"
redis_key_lp_completed_count: "lp_completed_count"
redis_key_lp_completed_yesterday_count: "lp_completed_yesterday_count"

