---
- set_fact: base_path_date="{{ lookup('pipe','date +%Y-%m') }}"

- set_fact: snapshot_date="snapshot_{{ lookup('pipe','date +%s') }}"

- name: Create snapshot repository
  uri:
    url: "http://{{ es_snapshot_host }}:9200/_snapshot/{{ snapshot_name }}?pretty"
    method: PUT
    headers:
      Content-Type: "application/json"
    body: "{{ snapshot_create_request_body | to_json }}"

- name: Take new snapshot
  uri:
    url: "http://{{ es_snapshot_host }}:9200/_snapshot/{{ snapshot_name }}/{{ snapshot_date }}?pretty"
    method: PUT
    headers:
      Content-Type: "application/json"

- name: Print all snapshots
  uri:
    url: "http://{{ es_snapshot_host }}:9200/_snapshot/{{ snapshot_name }}/_all?pretty"
    method: GET
    headers:
      Content-Type: "application/json"

- name: Print status of current snapshot
  uri:
    url: "http://{{ es_snapshot_host }}:9200/_snapshot/{{ snapshot_name }}/{{ snapshot_date }}?pretty"
    method: GET
    headers:
      Content-Type: "application/json"

- name: "Wait for backup to be completed"
  uri:
    url: "http://{{ es_snapshot_host }}:9200/_snapshot/{{ snapshot_name }}/{{ snapshot_date }}?pretty"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: result
  until: result.json.snapshots[0].state == 'SUCCESS'
  retries: 120
  delay: 10
