---
# vars file for deploy-ui-static
# For script
release_name: "{{ network_alias_content_tagging_service }}"
user_friendly_name: content_tagging service
template_compose_file_name: content_tagging.j2
template_env_file_name: content-tagging-service-env.j2
compose_file_name: "{{ service_content_tagging_service }}.yml"
env_file_name: "{{ service_content_tagging_service }}.env"
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_content_tagging_service }}.env"
#chart_path: "../kubernetes-deploy/content-tagging-service"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"

# For service
application_port: "{{ service_content_tagging_port }}"
image_name: "{{ image_content_tagging_service }}"
tag: "{{ tags_content_tagging_service }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_content_tagging_service }}"
reserved_memory: "{{ service_mem_reserved_content_tagging_service }}"
limited_memory: "{{ service_mem_limit_content_tagging_service }}"
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/healthcheck
network_alias_name: "{{ network_alias_content_tagging_service }}"
docker_service_stack_name: profanity
docker_service_name: "{{ service_content_tagging_service }}"
force_reload: "{{ force_reload_content_tagging_service }}"
