---
# vars file for deploy-lex-core-service

# For script
release_name: "{{ network_alias_frac_backend_service }}"
template_compose_file_name: frac_backend-service.j2
template_env_file_name: frac-backend-service-env.j2
compose_file_name: "{{ service_frac_backend_service }}.yml"
env_file_name: "{{ service_frac_backend_service }}.env"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_frac_backend_service }}.env"
#chart_path: "../kubernetes-deploy/frac-backend-service" 
env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"
user_friendly_name: frac_backend-service

# For service
application_port: "{{ service_frac_backend_port }}"
image_name: "{{ image_frac_backend_service }}"
tag: "{{ tags_frac_backend_service }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_frac_backend_service }}"
reserved_memory: "{{ service_mem_reserved_frac_backend_service }}"
limited_memory: "{{ service_mem_limit_frac_backend_service }}"
#limited_memory: 2048M
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/actuator/health
network_alias_name: "{{ network_alias_frac_backend_service }}"
docker_service_stack_name: lms
docker_service_name: "{{ service_frac_backend_service }}"
force_reload: "{{ force_reload_frac_backend_service }}"

# For application
server_connection_timeout: 5000
tomcat_max_threads: 400
tomcat_min_spare_threads: 20
servlet_multipart_max_file_size: 100Mb
servlet_multipart_max_request_size: 100Mb
spring_data_mongodb_uri: mongodb://{{ mongodb_user }}:{{ mongodb_password | urlencode }}@{{ mongodb_host }}:{{ mongodb_port }}/{{ mongodb_authentication_database }}
spring_data_mongodb_database: telemetry
spring_data_cassandra_bodhi_startupTimeoutInSeconds: 100



lhub_url: "{{ var_frac_backend_learning_hub_url }}"
lhub_certifaction_url: "{{ var_frac_backend_learning_hub_certification_url }}"
spring_datasource_jdbc_url: jdbc:postgresql://{{ postgresql_host }}:{{ postgresql_port }}/{{ postgresql_wingspan_database }}

enable_realtime_progress: "{{ var_frac_backend_enable_realtime_progress }}"

root_org: Infosys
instance_org: infy01
access_control_url: http://{{ network_alias_sb_ext_service }}:{{ service_sb_ext_port }}/accesscontrol
sb_learner_service_url: http://{{ sb_learner_service }}:{{ sb_learner_service_port }}/

wf_service_host: http://{{ network_alias_workflow_handler_service }}:{{ service_workflow_handler_port }}/

lms_service_host: http://lms-service:9000/
