---
# vars file for deploy-be-wat
# For script
release_name: "{{ network_alias_vega_web_service }}"
user_friendly_name: wat be-service 
#template_compose_file_name: ui-spv-igot.j2
template_env_file_name: "../../shared_files/templates/ui-shared-env.j2"
compose_file_name: "{{ service_vega_web_service }}.yml"
env_file_name: "{{ service_vega_web_service }}.env"
helm_env_file_location: "../helm_charts/igot-deploy/templates/"
helm_env_file_name: "{{ helm_env_file_location }}/{{ service_vega_web_service }}.env"
#chart_path: "../kubernetes-deploy/vega-web-service"

env_file_deployment_location: "{{ env_files_dir }}/{{ env_file_name }}"
compose_file_deployment_location: "{{ compose_files_dir }}/{{ compose_file_name }}"

# For service
application_port: "{{ service_vega_web_port }}"
image_name: "{{ image_vega_web_service }}"
tag: "{{ tags_vega_web_service }}"
host_port: "{{ application_port }}"
docker_port: "{{ application_port }}"
replicas: "{{ service_replicas_vega_web_service }}"
reserved_memory: "{{ service_mem_reserved_vega_web_service }}"
limited_memory: "{{ service_mem_limit_vega_web_service }}"
health_check_endpoint: http://127.0.0.1:{{ docker_port }}/healthcheck
network_alias_name: "{{ network_alias_vega_web_service }}"
docker_service_stack_name: ui
docker_service_name: "{{ service_vega_web_service }}"
force_reload: "{{ force_reload_vega_web_service }}"
