---
- name: backup exists
  file:
    path: "{{ backup_directory }}"
    state: directory
    mode: '0700'

- name: Perform PostgreSQL Backup
  template:
    src: postgres_backup.sh.j2
    dest: "{{ backup_directory }}/{{ backup_script_name }}"
    mode: '0700'

- name: Schedule PostgreSQL Backup in Jenkins
  jenkins_job:
    name: "PostgreSQL Backup Job"
    config: "{{ lookup('file', 'jenkins_job_config.xml') }}"
  when: jenkins_job_config is defined


